first commit
kosttiik/go-rest-api-homework pull request #1
Opened 2024-07-31 13:47 UTC by kosttiik

2024-07-31 14:54 UTC, just-musha requested changes
Привет! Неплохая работа, все основное сделано. Предлагаю немного доработать.

2024-07-31 14:54 UTC, just-musha commented on precode.go
> +	w.Write(resp)
Нужно проверить ошибку которую возвращает Write, достаточно залогировать в консоль будет

2024-07-31 14:54 UTC, just-musha commented on precode.go
> +	tasks[task.ID] = task
Здесь нужно проверить - есть ли уже такой ID. Если есть уже - то нужно вернуть ошибку пользвоателю. Иначе вместо создания - существующая задача будет перезатерта

2024-07-31 14:54 UTC, just-musha commented on precode.go
> +	w.Write(resp)
И тут проверить ошибку и залогировать

2024-07-31 14:54 UTC, just-musha commented on precode.go
> +	w.Write([]byte(fmt.Sprintf("Задача с ID %s удалена", id)))
Можно не возвращать тело ответа, достаточно статуса

2024-08-04 16:23 UTC, just-musha approved these changes
Да, принято! Статус - не крит для работы.

2024-08-04 16:23 UTC, just-musha commented on precode.go
> +		http.Error(w, "Задача с таким ID уже существует", http.StatusConflict)
Почему кстати выбрал этот статус? Выглядит так что у него немного другой смысл: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

2024-08-13 15:52 UTC, kosttiik commented on precode.go
> +		http.Error(w, "Задача с таким ID уже существует", http.StatusConflict)
@just-musha потому что согласно документации это конфликт текущего состояния ресурса (наличие задачи с таким айди) с запросом на изменение (создать задачку с таким же ID). Мне показалось, что это уместный код ошибки, который более точно передает суть проблемы

2024-08-21 13:09 UTC, just-musha commented on precode.go
> +		http.Error(w, "Задача с таким ID уже существует", http.StatusConflict)
@kosttiik да, звучит ок :ok:

2025-06-18 14:26 UTC, merged